import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const handleSeed = async () => {
  const salesData1 = [
    {
      year: "2025",
      month: "February",
      clientImageUrl: "/defaultPersonImage.png",
      clientName: "Client",
      clientEmail: "client@gmail.com",
      totalPayment: "100",
      paidAmount: "1000",
      remainingAmount: "0",
      description: "Description",
      organizationId: "37fa835e-aca0-40d3-8a32-e02af87f712c",
      memberId: "a097bf85-ddf0-4023-b04c-eb8eab90c2d0",
      createDate: "February-2025",
      createdAt: "Fri Feb 07 2025",
    },
    {
      year: "2025",
      month: "February",
      clientImageUrl: "/defaultPersonImage.png",
      clientName: "Client",
      clientEmail: "client@gmail.com",
      totalPayment: "100",
      paidAmount: "1000",
      remainingAmount: "0",
      description: "Description",
      organizationId: "37fa835e-aca0-40d3-8a32-e02af87f712c",
      memberId: "a097bf85-ddf0-4023-b04c-eb8eab90c2d0",
      createDate: "February-2025",
      createdAt: "Fri Feb 07 2025",
    },
    {
      year: "2025",
      month: "February",
      clientImageUrl: "/defaultPersonImage.png",
      clientName: "Client",
      clientEmail: "client@gmail.com",
      totalPayment: "200",
      paidAmount: "200",
      remainingAmount: "0",
      description: "Description",
      organizationId: "37fa835e-aca0-40d3-8a32-e02af87f712c",
      memberId: "a097bf85-ddf0-4023-b04c-eb8eab90c2d0",
      createDate: "February-2025",
      createdAt: "Fri Feb 07 2025",
    },
    {
      year: "2025",
      month: "February",
      clientImageUrl: "/defaultPersonImage.png",
      clientName: "Client",
      clientEmail: "client@gmail.com",
      totalPayment: "200",
      paidAmount: "100",
      remainingAmount: "0",
      description: "Description",
      organizationId: "37fa835e-aca0-40d3-8a32-e02af87f712c",
      memberId: "a097bf85-ddf0-4023-b04c-eb8eab90c2d0",
      createDate: "February-2025",
      createdAt: "Fri Feb 07 2025",
    },
    {
      year: "2025",
      month: "February",
      clientImageUrl: "/defaultPersonImage.png",
      clientName: "Client",
      clientEmail: "client@gmail.com",
      totalPayment: "100",
      paidAmount: "200",
      remainingAmount: "0",
      description: "Description",
      organizationId: "37fa835e-aca0-40d3-8a32-e02af87f712c",
      memberId: "a097bf85-ddf0-4023-b04c-eb8eab90c2d0",
      createDate: "February-2025",
      createdAt: "Fri Feb 07 2025",
    },
  ];
  const salesData2 = [
    {
      year: "2025",
      month: "March",
      clientImageUrl: "/defaultPersonImage.png",
      clientName: "Client",
      clientEmail: "client@gmail.com",
      totalPayment: "200",
      paidAmount: "1000",
      remainingAmount: "0",
      description: "Description",
      organizationId: "37fa835e-aca0-40d3-8a32-e02af87f712c",
      memberId: "a097bf85-ddf0-4023-b04c-eb8eab90c2d0",
      createDate: "March-2025",
      createdAt: "Fri Mar 07 2025",
    },
    {
      year: "2025",
      month: "March",
      clientImageUrl: "/defaultPersonImage.png",
      clientName: "Client",
      clientEmail: "client@gmail.com",
      totalPayment: "1000",
      paidAmount: "1000",
      remainingAmount: "0",
      description: "Description",
      organizationId: "37fa835e-aca0-40d3-8a32-e02af87f712c",
      memberId: "a097bf85-ddf0-4023-b04c-eb8eab90c2d0",
      createDate: "March-2025",
      createdAt: "Fri Mar 07 2025",
    },
    {
      year: "2025",
      month: "March",
      clientImageUrl: "/defaultPersonImage.png",
      clientName: "Client",
      clientEmail: "client@gmail.com",
      totalPayment: "1000",
      paidAmount: "200",
      remainingAmount: "0",
      description: "Description",
      organizationId: "37fa835e-aca0-40d3-8a32-e02af87f712c",
      memberId: "a097bf85-ddf0-4023-b04c-eb8eab90c2d0",
      createDate: "March-2025",
      createdAt: "Fri Mar 07 2025",
    },
    {
      year: "2025",
      month: "March",
      clientImageUrl: "/defaultPersonImage.png",
      clientName: "Client",
      clientEmail: "client@gmail.com",
      totalPayment: "200",
      paidAmount: "200",
      remainingAmount: "0",
      description: "Description",
      organizationId: "37fa835e-aca0-40d3-8a32-e02af87f712c",
      memberId: "a097bf85-ddf0-4023-b04c-eb8eab90c2d0",
      createDate: "March-2025",
      createdAt: "Fri Mar 07 2025",
    },
    {
      year: "2025",
      month: "March",
      clientImageUrl: "/defaultPersonImage.png",
      clientName: "Client",
      clientEmail: "client@gmail.com",
      totalPayment: "200",
      paidAmount: "200",
      remainingAmount: "0",
      description: "Description",
      organizationId: "37fa835e-aca0-40d3-8a32-e02af87f712c",
      memberId: "a097bf85-ddf0-4023-b04c-eb8eab90c2d0",
      createDate: "March-2025",
      createdAt: "Fri Mar 07 2025",
    },
  ];
  const salesData3 = [
    {
      year: "2025",
      month: "April",
      clientImageUrl: "/defaultPersonImage.png",
      clientName: "Client",
      clientEmail: "client@gmail.com",
      totalPayment: "1000",
      paidAmount: "1000",
      remainingAmount: "0",
      description: "Description",
      organizationId: "37fa835e-aca0-40d3-8a32-e02af87f712c",
      memberId: "a097bf85-ddf0-4023-b04c-eb8eab90c2d0",
      createDate: "April-2025",
      createdAt: "Fri Apr 07 2025",
    },
    {
      year: "2025",
      month: "April",
      clientImageUrl: "/defaultPersonImage.png",
      clientName: "Client",
      clientEmail: "client@gmail.com",
      totalPayment: "1000",
      paidAmount: "1000",
      remainingAmount: "0",
      description: "Description",
      organizationId: "37fa835e-aca0-40d3-8a32-e02af87f712c",
      memberId: "a097bf85-ddf0-4023-b04c-eb8eab90c2d0",
      createDate: "April-2025",
      createdAt: "Fri Apr 07 2025",
    },
    {
      year: "2025",
      month: "April",
      clientImageUrl: "/defaultPersonImage.png",
      clientName: "Client",
      clientEmail: "client@gmail.com",
      totalPayment: "1000",
      paidAmount: "1000",
      remainingAmount: "0",
      description: "Description",
      organizationId: "37fa835e-aca0-40d3-8a32-e02af87f712c",
      memberId: "a097bf85-ddf0-4023-b04c-eb8eab90c2d0",
      createDate: "April-2025",
      createdAt: "Fri Apr 07 2025",
    },
    {
      year: "2025",
      month: "April",
      clientImageUrl: "/defaultPersonImage.png",
      clientName: "Client",
      clientEmail: "client@gmail.com",
      totalPayment: "1000",
      paidAmount: "1000",
      remainingAmount: "0",
      description: "Description",
      organizationId: "37fa835e-aca0-40d3-8a32-e02af87f712c",
      memberId: "a097bf85-ddf0-4023-b04c-eb8eab90c2d0",
      createDate: "April-2025",
      createdAt: "Fri Apr 07 2025",
    },
    {
      year: "2025",
      month: "April",
      clientImageUrl: "/defaultPersonImage.png",
      clientName: "Client",
      clientEmail: "client@gmail.com",
      totalPayment: "1000",
      paidAmount: "1000",
      remainingAmount: "0",
      description: "Description",
      organizationId: "37fa835e-aca0-40d3-8a32-e02af87f712c",
      memberId: "a097bf85-ddf0-4023-b04c-eb8eab90c2d0",
      createDate: "April-2025",
      createdAt: "Fri Apr 07 2025",
    },
  ];
  try {
    // Sales Date 1
    salesData1.forEach(async (data) => {
      await prisma.sale.create({
        data: {
          year: data.year,
          month: data.month,
          clientImageUrl: data.clientImageUrl,
          clientName: data.clientName,
          clientEmail: data.clientEmail,
          totalPayment: data.totalPayment,
          paidAmount: data.paidAmount,
          remainingAmount: data.remainingAmount,
          description: data.description,
          organizationId: data.organizationId,
          memberId: data.memberId,
          createDate: data.createDate,
          createdAt: data.createdAt,
        },
      });
    });
    // Sales Date 2
    salesData2.forEach(async (data) => {
      await prisma.sale.create({
        data: {
          year: data.year,
          month: data.month,
          clientImageUrl: data.clientImageUrl,
          clientName: data.clientName,
          clientEmail: data.clientEmail,
          totalPayment: data.totalPayment,
          paidAmount: data.paidAmount,
          remainingAmount: data.remainingAmount,
          description: data.description,
          organizationId: data.organizationId,
          memberId: data.memberId,
          createDate: data.createDate,
          createdAt: data.createdAt,
        },
      });
    });
    // Sales Date 3
    salesData3.forEach(async (data) => {
      await prisma.sale.create({
        data: {
          year: data.year,
          month: data.month,
          clientImageUrl: data.clientImageUrl,
          clientName: data.clientName,
          clientEmail: data.clientEmail,
          totalPayment: data.totalPayment,
          paidAmount: data.paidAmount,
          remainingAmount: data.remainingAmount,
          description: data.description,
          organizationId: data.organizationId,
          memberId: data.memberId,
          createDate: data.createDate,
          createdAt: data.createdAt,
        },
      });
    });
  } catch (error) {
    console.log(error);
  }
};

handleSeed();
